version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # or GitHub Actions, set the directory to / to check for workflow files in .github/workflows.
    directory: '/'
    target-branch: "version-2.03"
    schedule:
      interval: 'daily'

  # Enable version updates for python
  - package-ecosystem: 'pip'
  # Look for `requirements.txt` file
    directory: '/'
    target-branch: "version-2.03"
    schedule:
      interval: 'daily'
