# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI_Tests

on:
  push:
    paths-ignore:
      - "README.rst"
      - "**/dependabot.yml"
    branches: [version-2.03]
  pull_request:
    paths-ignore:
      - "README.rst"
      - "**/dependabot.yml"
    branches: [version-2.03]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install xmllint
        run: sudo apt-get install libxml2-utils
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: xmllint the schema
        run: xmllint --schema http://www.w3.org/2001/XMLSchema.xsd --noout *.xsd
      - name: Run complete schema test suite
        run: ./tests/run-tests.sh
      - name: Pytest
        run: pytest

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
